name: "manged_example"

entrypoint: >-
  python3 -m determined.launch.torch_distributed
  python3 distributed_managed.py

resources:
  slots_per_trial: 2

searcher:
   name: single
   metric: test_loss
   max_length: 1
   
hyperparameters:
   epochs: 5
   batch_size: 64
   test_batch_size: 1000
   learning_rate: 0.0001
   gamma: 0.7
   n_filters1: 8
   n_filters2: 8
   dropout1: 0.2
   dropout2: 0.2

max_restarts: 0

workspace: "Bijan"
project: "test"